baseURL = "https://ngfgrant.github.io/scrum/"
languageCode = "en-gb"
title = "Github Scrum"
themesDir = "themes"
theme = "hugo-whisper-theme"
publishDir = "docs"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'scrum is a simple command line utility that provides useful scrum metrics to assist a Scrum team in their Transparency, Inspection and Adaptation.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "scrum is a CLI that makes scrum easy on GitHub."
    meta_og_title = "GitHub Scrum"
    meta_og_type = "website"
    meta_og_url = "https://ngfgrant.github.io/scrum"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "A CLI that help you run Scrum on GitHub."

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
